### ISSUE TITLE
Gaining XP in a skill post level 99 will continually cause the plugin to notify you

### ISSUE THREAD

**Issue by EleanaOSRS** [Vanillj/XpToLevelNotification#2]
![image](https://user-images.githubusercontent.com/39443935/190360591-10e104a4-0aa6-4b59-901e-6c83d8c4d907.png)

**Comment by R-Dson** [comment]
Thanks for reporting this. Oddly, I tried it myself and can't get negative values like yours no matter which levels I try. 
What level are you? 
Is is the correct XP left the same but just negative?

**Comment by EleanaOSRS** [comment]
The negative numbers don't correlate to all the post 99 xp. I have ~19.5m xp in Hitpoints and 14.6m xp in Strength. If I subtract the xp from the plugin from Hitpoints and Strength, they both seem to come out to ~14,391,160 xp. I tried triggering the notification with another post 99 skill, but it didn't work, not sure if this is because the XP in that skill is only at 13.5m xp.

**Comment by R-Dson** [comment]
Interesting, I'll look into it. 14,391,160 xp is exactly the virtual level 100 so it is probably an issue with xp/levels past that.

**Comment by R-Dson** [comment]
This should now be solved in 70666cdd7003dff6b0560eee4c32469cb3f11cd6. Thanks you!
